### ISSUE TITLE
Publish to NPM registry

### ISSUE THREAD

**Issue by JamieSlome** [finos/git-proxy#114]
To make Git Proxy easy to consume, we should onboard the project to [NPM](https://www.npmjs.com/).

@maoo, what do we need from your end to get this published under the FINOS namespace?

**Comment by maoo** [comment]
Hi @JamieSlome !

Here's what we need to do:
1. @TheJuanAndOnly99 - could you please generate a new NPM token and set it as secret on the `git-proxy` repo, with name `NPM_TOKEN`? Please ping us here when it's all done.
2. @JamieSlome - could you please work on a github action that publishes the package? See https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
3. @JamieSlome - I see that version is still `0.0.1` ; prior to the release, I'd consider raising this number to `0.1.0`, and maybe map future `0.x.0` to future important releases, WDYT?
4. @JamieSlome - could you please ping marketing [at] finos [dot] org and share some dates and contents with them, so that we can share the great news with our community? /cc @grizzwolf @niamhoparker @winmorgan

Feel free to reach out to help [at] finos [dot] org if you need any help or support.

**Comment by TheJuanAndOnly99** [comment]
@maoo @JamieSlome The `NPM_TOKEN` secret is set.

**Comment by JamieSlome** [comment]
@TheJuanAndOnly99 - thank you!

**Comment by JamieSlome** [comment]
@maoo:

1. I'll start the GitHub Action on the attached development branch for this issue.
2. I'd say we should map our first release to `1.0.0` as we are releasing **major** functionality for the library. We will follow `semver` moving forward.
3. Once I've got the publication action up and running, I'll let you know and we can proceed with a community announcement.

**Comment by JamieSlome** [comment]
PR ready to go 👍 Feedback welcome! @maoo

**Comment by JamieSlome** [comment]
Published 🎉 
[@finos/git-proxy](https://www.npmjs.com/package/@finos/git-proxy/v/1.0.0) on NPM 👍 

Thanks @maoo @TheJuanAndOnly99...
