### ISSUE TITLE
GitProxy HTTPS support

### ISSUE THREAD

**Issue by msagi** [finos/git-proxy#546]
**Is your feature request related to a problem? Please describe.**
GitProxy supports HTTP only for the git proxy interface. HTTP communication is not encrypted and therefore not secure to send sensitive information through.

**Describe the solution you'd like**
Add HTTPS support to the git proxy interface to increase overall security of the solution.

**Describe alternatives you've considered**
Running GitProxy locally only, so communication does not leave localhost... but this severely limits the usability of GitProxy as an enterprise gateway to open source hubs.

**Comment by maoo** [comment]
@msagi - I've played a bit on this and got something to work; let me explain.

Adding HTTPS support to express is trivial, so trivial that fits in a screenshot 😄 

<img width="1171" alt="Screenshot 2024-05-10 at 16 12 06" src="https://github.com/finos/git-proxy/assets/327285/e0280cb8-11b0-4244-b88a-1ba95b6343d3">

The certificates were generated with one command:

```
openssl req -x509 -newkey rsa:4096 -keyout certs/key.pem -out certs/cert.pem -sha256 -days 3650 -nodes -subj "/C=US/ST=NY/L=New York/O=FINOS/OU=CTI/CN=localhost"
```

Of course, the path to certificates should be stored in (and fetched from) `proxy.config.json`, but that's a simple change.

In order to test it locally, using self-signed certificates, you'll have to add `-c http.sslVerify=false` to the `git clone` command.

If you like what you see, I can work on a proper PR, with docs changes and proper configuration.

Eager to hear your feedback!

**Comment by maoo** [comment]
@msagi - here's the code #558 ; I also invited you as a Git Proxy Contributor (a GitHub Team), to grant you Triage permissions , so that I can set you as PR reviewer.

**Comment by JamieSlome** [comment]
@maoo @msagi - #558 has been merged 👍 Are we happy to close this issue?
